s = set ()
n = input("enter your name : ")
s.add(int(n))
n = input("enter your name : ")
s.add(int(n))
n = input("enter your name : ")
s.add(int(n))
n = input("enter your name : ")
s.add(int(n))
n = input("enter your name : ")
s.add(int(n))
n = input("enter your name : ")
s.add(int(n))
n = input("enter your name : ")
s.add(int(n))
n = input("enter your name : ")
s.add(int(n))
print ( s )